name: Windows - Build Examples
on: [push, pull_request]

jobs:
  windows-build:
    name: Windows - Build Examples
    runs-on: windows-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
          irm get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          echo ("PATH=" + $env:PATH + ";" + $home + "\scoop\shims") >> $env:GITHUB_ENV
          scoop bucket add crystal-preview https://github.com/neatorobito/scoop-crystal
          scoop install vs_2022_cpp_build_tools
          scoop install crystal
      - name: shards install
        run: shards install
      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4
      - name: raylib-cr post-install
        run: |
          powershell lib/raylib-cr/rsrc/install-ga.ps1
          echo ("LIB=" + $env:LIB + ";" + $pwd + "\libs") >> $env:GITHUB_ENV
          echo ("PATH=" + $env:PATH + ";" + $pwd + "\libs") >> $env:GITHUB_ENV
      - name: Build examples
        run: crystal run rsrc/build-examples/build.cr